name: Build Release Macos
on:
  push:
    branches: ["main"]
    tags:
      - '*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none

jobs:
  build_macos:
    if: github.repository_owner == 'myridia'
    runs-on: macos-15
    steps:
      - name: get_repository
        run: |
          brew install rust rustc-completion
   
      - name: checkout repo
        uses: actions/checkout@v4

      - name: check_xcode
        run: |
          xcode-select --install
          
      - name: add_targets
        run: |
          #rustup target list
          rustup target add x86_64-apple-darwin
          echo "Installed Targets:"
          rustup target list --installed
          
    
      - name: compile macos
        run: |
          cargo build --target x86_64-apple-darwin --release 
          cargo clean 
          #cargo build  --release 


          
