name: release_macos
on:
  workflow_run:
    workflows: ["release_linux"]
    types:
      - completed


permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none

jobs:
  build_macos:
    if: github.repository_owner == 'myridia'
    runs-on: macos-15
    steps:
      - name: get_repository
        run: |
          brew install rust rustc-completion
   
      - name: checkout repo
        uses: actions/checkout@v4

      - name: add_targets
        run: |
          #rustup target list
          rustup target add x86_64-apple-darwin
          echo "Installed Targets:"
          rustup target list --installed
          
    
      - name: compile macos
        run: |
          # cargo build --target x86_64-apple-darwin --release 
          cargo clean 
          cargo build  --release
          ls target/release
          cp target/release/rate target/release/rate_macos

      - name: Upload Macos Binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'target/release/rate_macos'
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true   
        
