name: SCP Deploy

on:
  workflow_run:
    workflows: ["release_linux"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'myridia'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: SCP files to server
        run: |
          wget https://github.com/myridia/rate/releases/download/main/rate_linux -O mrate
          chmod 777 mrate
          echo "...list root folder"
          ls -all
          echo "...upload."
          scp mrate ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.SERVER_PATH }}
          echo "...restart"
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "systemctl restart mrate"



