name: create ssh kyes

on:
  push:
    branches: ["main"]
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none

jobs:
  # Single deploy job since we're just deploying
  build_linux:
    if: github.repository_owner == 'myridiax'
    runs-on: ubuntu-22.04  
    steps:
      - name: make ssh key
        run: |
         mkdir ~/.ssh 
         ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -N ""
         echo "list keys"
         ls ~/.ssh
         echo "public key"
         cat ~/.ssh/id_ed25519.pub
         echo "private key"
         cat ~/.ssh/id_ed25519

         
         
      
      
      
      
      
      
      
      
          
